### ISSUE TITLE
Media editor overlay UI issues with a lot of custom image sizes

### ISSUE THREAD

**Issue by ryanurban** [sirulli/yoimages#32]
Hey guys,

First of all, nice work on this plugin!

I have been using this plugin on a project recently, and have come across an issue when I have a lot of custom image sizes in the media overlay that pops up for editing crop formats:

<a href="https://cloudup.com/cUqWmotJGit">Screenshot</a>

If I can be of assistance in helping fix this, just let me know. I'm assuming this is a matter of updating styles and possibly some JS. Another, potentially better and maybe simpler (based on playing with the CSS & JS a bit and realizing a good bit of it is coming from WordPress) idea might be implementing a select input to allow the selection of an image size to customize.

Thanks!

![screen shot 2015-04-27 at 9 23 02 pm](https://cloud.githubusercontent.com/assets/840559/7361402/a3a03eb6-ed25-11e4-9ed8-f8326acbc8fc.png)

**Comment by ferrbea** [comment]
Hi Ryan,
thanks for getting in touch with us. 

We went through this case and we came up with the idea of solving it the same way firefox solves the issue of too many tabs open at the same time (see<a href="http://i.imgur.com/K4suEOd.png"> screenshot here</a>) instead of using a select input.

What do you think? Would this be a good solution in your opinion?
Are you interested in contributing to the plugin by implementing it by yourself?
We will then give you credit in the plugin page.

Thanks
Team Sirulli

**Comment by fagia** [comment]
Fixed in release 0.1.1
